version: '3'

services:
  app_db:
    build: ./
    command: ./wait-for-postgres.sh db ./botPageSaver
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DATABASE_URL:  "postgres://postgres:postgres@db:5432/postgres?sslmode=disable"
      DB_PASSWORD: "postgres"
      TG_TOKEN: ""

  db:
    restart: always
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: postgres
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    ports:
      - "5436:5432"


